# -*- coding: utf-8 -*-
"""reddit_scraper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IlDP6zYBMNbUzAzSJ2flfKKadnafIOOL
"""

import pandas as pd
from prawcore.exceptions import Forbidden

# Import Libraries
import praw

def scrape():
  try:
    # Please change with your own client id, client secret, and user agent
    # Initializing the client id, client secret, and user agent
    reddit = praw.Reddit(client_id= '', #Enter your client id
                     client_secret= '', #Enter your secret key
                     user_agent= '', #Enter your client user agent
                     check_for_async = False)

    hot_posts = reddit.subreddit('r/chile').search('cáncer', sort='hot', limit=10000)   #Please change with your the subreddit of your choice

    for post in hot_posts:
      # Title of each post
      posts_dict["Title"].append(post.title)

      # Text inside a post
      posts_dict["Post Text"].append(post.selftext)

      # Unique ID of each post
      posts_dict["ID"].append(post.id)

      # The score of a post
      posts_dict["Score"].append(post.score)

      # Total number of comments inside the post
      posts_dict["Total Comments"].append(post.num_comments)

      # URL of each post
      posts_dict["Post URL"].append(post.url)

    # Fetching the reddits
    reddit_posts = []
    for post in hot_posts:
      reddit_posts.append(post.selftext)

  except Forbidden:
       print("We\'ve been banned!")
  return reddit_posts

posts_dict = {"Title": [], "Post Text": [],
              "ID": [], "Score": [],
              "Total Comments": [], "Post URL": []
              }

hot_posts = scrape()
print(len(posts_dict['Post Text']))   #Number of posts scraped

# Saving the data in a pandas dataframe
top_posts = pd.DataFrame(posts_dict)
top_posts.to_excel("file_op_path/output.xlsx", index=True)   #Enter the file output path